version: "3.8"
# services / containers
services:
    # express app
    web-udaputera-portfolio:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web-udaputera-portfolio
        image: web-udaputera-portfolio:1.0.0
        restart: always
        ports:
            - 3010:3000
        environment:
            NUXT_PUBLIC_API_URI: https://api.uda.portfolio.udaputera.com
