# services / containers
services:
    # express app
    web-udaputera-portfolio:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web-udaputera-portfolio
        image: web-udaputera-portfolio:1.0.15
        restart: always
        ports:
            - 3010:3000
        networks:
            - app-uda-portfolio
        environment:
            NUXT_API_URL: https://api.uda.portfolio.udaputera.com
            NUXT_PUBLIC_API_URL: https://api.uda.portfolio.udaputera.com

# networks
networks:
    app-uda-portfolio:
        name: app-uda-portfolio
        driver: bridge
